# `Linear Algebra using Numpy`

# <font color=red>Mr Fugu Data Science</font>

# (◕‿◕✿)

# `Purpose & Outcome:`

+ Learn new numpy operations
+ Practice linear algebra
    + brush up on how operations work by example

**Help Support the Channel: Buy Me A Coffee @mrfugudatasci**

In [1]:
import numpy as np
np.__version__ # if you were wondering what version

'1.18.1'

# `Eigen values and vectors:`

<font size=4>**$Ax=\lambda x$**</font>, where **$\lambda$** is our eigen value of A
+ It deals with shrinking and stretching of vector ( x )
    + If the eigenvalue is zero, then we have a nullspace
+ the determinant <font size=4>$(A-\lambda I)=0$</font>


`------------------------------`
+ If you have a square matrix consider using: `np.linalg.eigh( )` for speed

# Ex.)  $$A=\begin{bmatrix} 1 & 0 \\ -3 & 2  \end{bmatrix}$$

Let us solve this:

$det\begin{bmatrix} 1-\lambda & 0 \\ -3& 2-\lambda   \end{bmatrix}$

$=(1-\lambda)(2-\lambda)-(3)*(0)$

`factor this and use completing the squares`

$=\lambda^2-3\lambda+2$

$=(\lambda-1)(\lambda-2)$

$\lambda=1,2$ `finally our eigen values yippie.`

`---------------------------`

`Eigen Vectors`

Can solve with `Gaussian Elimination:`

[theory eigenvalue/vectors M.I.T help](http://math.mit.edu/~gs/linearalgebra/ila0601.pdf) | [matrix calculator with steps shown](https://matrixcalc.org/en/vectors.html#eigenvectors%28%7B%7B1,0%7D,%7B-3,2%7D%7D%29)

In [ ]:
%%timeit
a = np.array([[1,0], [-3,2]])
eigenvalues, eigenvectors = np.linalg.eig(a)
# Note: use eigh if your matrix is symmetric (faster)
eigenvalues,eigenvectors

In [2]:
a = np.array([[1,0], [-3,2]])
eigenvalues, eigenvectors = np.linalg.eig(a)

eigenvalues,eigenvectors


(array([2., 1.]),
 array([[0.        , 0.31622777],
        [1.        , 0.9486833 ]]))

# `Hermitian Matrix:`

<font size=4>$A^{\theta}=A^T$</font>, the conjugate of (A) equals (A) transpose

$A=\begin{bmatrix} 6&2-j&4 \\ 2+j&-3&-j\\4&j&9   \end{bmatrix}$

`then`
$A^{\theta}=\begin{bmatrix} 6&2+j&4 \\ 2-j&-3&j\\4&-j&9   \end{bmatrix}$ = $A^T=\begin{bmatrix} 6&2+j&4 \\ 2-j&-3&j\\ 4&-j&9  \end{bmatrix}$

In [ ]:
%%timeit
eigenvalues, eigenvectors = np.linalg.eigh(a)
eigenvalues, eigenvectors

In [8]:
a = np.array([[1,0], [-3,2]])
eigenvalues, eigenvectors = np.linalg.eigh(a)
eigenvalues, eigenvectors
np.linalg.eigh(a_)

(array([-1.54138127,  4.54138127]),
 array([[-0.76301998, -0.6463749 ],
        [-0.6463749 ,  0.76301998]]))

# `Trace:`


In [ ]:
# offset trace:

In [ ]:
# transpose and Inverse

In [ ]:
# systems of equations:

In [ ]:
# np.cross

In [ ]:
# 

In [ ]:
# `Banded Matrices:`

# `Using Least Squares: np.linalg.lstsq(A,b)`
+ Under the hood uses SVD

# `Solving Linear Systems with: np.linalg.solve()`
+ (A) must be a square and full-rank matrix: All of its 
rows must be be linearly independent. 
+ (A) should be invertible/non-singular (its determinant is not zero)

# Ex.) two equations and two unknowns

$x_1+x_2=30$

$6x_1+2.3x_2=44$


we will use `Ax=b` to solve this problem


In [ ]:
# Ax=b -> [A^-1]*b, but dont directly instead with .solve()
A = np.array([[1,1],[6,2.3]])
b= np.array([30,44])

np.linalg.solve(A,b)

In [ ]:
%%timeit
np.linalg.solve(A,b)

# `we could use: np.linalg.inv(A).dot(B)`

To solve the problem from above, but there is a caveat and considerations.
+ When using numpy we have two options to solve this problem, one is faster than the other.
Let's take into account our other option and how it can inhibit our computations/time.

+ We are starting with `Ax=b ->`$x=A^{-1}*b$ but computing the inverse is time consuming for a few reasons as well as resources allocated.

`Direct version`
Let's understand how `np.linalg.solve()` works.
+ we are not calculating the inverse, instead we are using LAPACK routine.
    + Then LU decomposition is used to find the values using forward/back substitution.
 
`Slower version & (can be) Not as accurate`
Now, `np.linalg.inv(A).dot(B)`
+ you are using more floating point operations to solve the inverse
    + If (A) is an ill-conditioned matrix you will have inaccuracy
    + useless steps that are unneeded while computing
 
[.solve() vs .inv.dot()](https://stackoverflow.com/questions/31256252/why-does-numpy-linalg-solve-offer-more-precise-matrix-inversions-than-numpy-li) | [LAPACK background](http://www.netlib.org/lapack/)

In [ ]:
np.linalg.inv(A).dot(b)

In [ ]:
%%timeit
np.linalg.inv(A).dot(b)

In [ ]:
# `Least Squares:` 

In [ ]:
# Outer product

In [ ]:
# Dot Product, 

# `Matrix Multiplication:`

<font size=4>$A=\begin{bmatrix} 1&2&3&4 \\ 5&6&7&8\\9&10&11&12   \end{bmatrix}_{ 3x4}$
,$B=\begin{bmatrix} 2&4&6 \\ 8&10&12\\14&16&18  \end{bmatrix}_{ 3x3}$</font>

we have a $(3x4)(3x3)=(?)$, depends transpose and order of matrices `3x4 or 4x3`

<font size=4>$[A^TB]_{3x4}$ versus $[BA^T]_{3x4}$</font>

`Order MATTERS~`

# `Rank:`



# `Multiple Linear Regression:`

<font size=4>$$</font>

# <font color=red>Like</font>,Share &

# <font color=red>SUB</font>scribe

**`Help Support the channel: Buy Me A Coffee @mrfugudatasci`**

# `Citations & Help:`

# ◔̯◔

https://www.bogotobogo.com/python/python_numpy_matrix_tutorial.php

https://www.twilio.com/blog/2018/06/data-science-linear-algebra-python-scipy-numpy.html

http://www2.lawrence.edu/fast/GREGGJ/Python/numpy/numpyLA.html

https://web.stanford.edu/class/cs231a/section/section1.pdf

http://snowball.millersville.edu/~adecaria/ESCI386P/esci386-lesson18-Linear-Algebra.pdf

https://courses.cs.washington.edu/courses/cse446/20wi/Section1/linear_algebra.html

https://sites.calvin.edu/scofield/courses/m256/materials/eigenstuff.pdf